version: '3.8'

services:
  web:
    build: .
    ports:
      - "7755:7755"  # Map port 7755 on the host to port 7755 on the container
    environment:
      - PYTHONUNBUFFERED=1  # Prevents Python from buffering stdout and stderr
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: gunicorn -w 4 -b 0.0.0.0:7755 core.server:app  # Command to run the application